import type { PlaylistDef } from "@/content/question-types";

/**
 * Curated playlists for the v2 question bank.
 *
 * Each playlist is a hand-ordered list of question slugs. The playlist page
 * resolves slugs to full Question rows and renders them in this order.
 *
 * A question can appear in multiple playlists. The `top-50` showcase
 * intentionally pulls from every topic so a brand-new visitor sees a
 * representative sample without first picking a track.
 */
export const PLAYLISTS: PlaylistDef[] = [
  {
    slug: "warmup-quickstart",
    name: "Warmup Quickstart",
    description:
      "A short ramp: mental math, core probability, and a few 'bank primitives' so you can start submitting answers immediately.",
    hero_emoji: "🔥",
    question_slugs: [
      "sum-1-to-100-mental-math-mcq",
      "coin-game-advantage",
      "expected-rolls-until-6-freeform",
      "expected-coin-flips-until-heads-freeform",
      "expected-tries-to-get-6-two-dice-mcq",
      "probability-three-coin-same-side-mcq",
      "monty-hall-switch",
      "two-children-at-least-one-boy",
      "disease-test-bayes",
      "birthday-23",
      "expected-rolls-until-six",
      "coupon-collector-four",
      "max-of-two-dice",
      "stick-broken-triangle",
      "variance-binomial-100-half",
      "ev-uniform-zero-one-square",
      "clt-distribution-mcq",
      "dynamic-array-amortized-mcq",
      "vector-iterator-invalidation-mcq",
      "sys-process-vs-thread-freeform",
    ],
  },
  {
    slug: "researcher-foundations",
    name: "Researcher Foundations",
    description:
      "The probability + statistics core every quant researcher interview leans on. Bayes, expectation, variance scaling, order statistics, random walks.",
    hero_emoji: "📐",
    question_slugs: [
      "law-of-total-probability-mcq",
      "probability-union-bound-mcq",
      "markov-inequality-mcq",
      "chebyshev-inequality-mcq",
      "memoryless-property-exponential-mcq",
      "two-dice-sum-seven",
      "geometric-first-head-third-flip",
      "expected-rolls-until-sum-seven",
      "expected-trials-until-first-success-geometric",
      "disease-test-bayes",
      "monty-hall-switch",
      "two-children-at-least-one-boy",
      "birthday-23",
      "ace-in-five-card-hand",
      "coupon-collector-four",
      "hat-check-fixed-points",
      "gamblers-ruin-fair",
      "random-walk-return-step-2",
      "ev-min-two-uniforms",
      "var-of-sample-mean-numeric",
      "clt-distribution-mcq",
    ],
  },
  {
    slug: "researcher-advanced",
    name: "Researcher Advanced (ML + Time Series + Stochastic)",
    description:
      "A higher-signal set on evaluation/leakage, stationarity, and stochastic process intuition.",
    hero_emoji: "🧠",
    question_slugs: [
      "ml-train-test-leakage-examples-freeform",
      "ml-hyperparameter-tuning-leakage-freeform",
      "ml-nested-cross-validation-why-freeform",
      "ml-calibration-vs-discrimination-freeform",
      "ml-platt-vs-isotonic-calibration-freeform",
      "ml-temperature-scaling-what-freeform",
      "ml-importance-weighting-covariate-shift-freeform",
      "ts-stationarity-definition-freeform",
      "ts-adf-null-hypothesis-mcq",
      "ts-kpss-null-hypothesis-mcq",
      "ts-adf-kpss-disagree-why-freeform",
      "ts-acf-vs-pacf-heuristic-freeform",
      "ts-ma1-acf-what-is-it-freeform",
      "ts-walk-forward-validation-freeform",
      "ts-walk-forward-scaling-leakage-freeform",
      "ts-cointegration-intuition-freeform",
      "ts-engle-granger-two-step-intuition-freeform",
      "ito-intuition-freeform",
      "quadratic-variation-bm-freeform",
      "strong-markov-property-what-is-it-freeform",
    ],
  },
  {
    slug: "quant-dev-essentials",
    name: "Quant Dev Essentials",
    description:
      "Algorithms, data structures, concurrency reasoning, and low-level design — the SWE side of the trading-firm interview loop.",
    hero_emoji: "⚙️",
    question_slugs: [
      "sys-p99-vs-mean-why-freeform",
      "sys-file-descriptor-what-is-it-freeform",
      "sys-process-vs-thread-freeform",
      "sys-time-wait-why-so-many-freeform",
      "sys-epoll-edge-triggered-pitfall-freeform",
      "vector-iterator-invalidation-mcq",
      "dynamic-array-amortized-mcq",
      "unordered-map-rehash-latency-freeform",
      "bloom-filter-what-why-freeform",
      "bloom-filter-fpr-tradeoff-mcq",
      "spinlock-vs-mutex-when-freeform",
      "notify-one-vs-notify-all-freeform",
      "condition-variable-missed-wakeup-why-freeform",
      "false-sharing-explain",
      "aba-problem-explain",
      "lld-circuit-breaker",
      "lld-dedup-cache-ttl",
      "lld-ring-buffer-logger",
      "lld-fixed-capacity-hashmap",
      "sysdesign-backpressure-streaming",
      "sysdesign-kill-switch",
      "online-vwap-intervals",
      "rolling-bid-ask-spread-window-k",
    ],
  },
  {
    slug: "quant-dev-low-latency-core",
    name: "Quant Dev Low-Latency Core",
    description:
      "Deeper: C++ gotchas, atomics/memory ordering, and system-level latency pitfalls.",
    hero_emoji: "🧵",
    question_slugs: [
      "sys-clock-sources-monotonic-freeform",
      "sys-cacheline-false-sharing-diagnose-freeform",
      "sys-busy-polling-why-freeform",
      "sys-tcp-retransmits-what-causes-freeform",
      "sys-sendfile-vs-splice-freeform",
      "cpp-atomic-memory-order-when-mcq",
      "cpp-atomic-false-sharing-why-freeform",
      "cpp-hidden-allocations-hot-path-freeform",
      "cpp-shared-ptr-aliasing-ctor-why-freeform",
      "cpp-atomic-ref-what-when-freeform",
      "cpp-lifetime-of-temporary-extension-freeform",
      "cas-loop-backoff-why-freeform",
      "atomic-rmw-contention-why-freeform",
      "fairness-vs-throughput-locks-freeform",
      "lock-convoy-what-is-it-freeform",
      "sysdesign-latency-slo-budgeting",
      "sysdesign-observability-low-latency",
      "sysdesign-tick-to-trade-measurement",
    ],
  },
  {
    slug: "top-50",
    name: "Top 50",
    description:
      "A mixed showcase across every topic. Use this if you don't know where to start.",
    hero_emoji: "⭐",
    question_slugs: [
      "monty-hall-switch",
      "two-children-at-least-one-boy",
      "disease-test-bayes",
      "expected-flips-until-hh",
      "max-of-two-dice",
      "coupon-collector-four",
      "birthday-23",
      "stick-broken-triangle",
      "gamblers-ruin-fair",
      "secretary-named-theorem",
      "variance-binomial-100-half",
      "ev-min-two-uniforms",
      "clt-distribution-mcq",
      "prob-up-after-two-signals",
      "dynamic-array-amortized-mcq",
      "unordered-map-rehash-latency-freeform",
      "bloom-filter-what-why-freeform",
      "spinlock-vs-mutex-when-freeform",
      "notify-one-vs-notify-all-freeform",
      "false-sharing-explain",
      "aba-problem-explain",
      "cpp-virtual-destructor-why-mcq",
      "cpp-move-vs-copy-when-happens-freeform",
      "sys-p99-vs-mean-why-freeform",
      "sys-time-wait-why-so-many-freeform",
      "lld-circuit-breaker",
      "lld-config-hot-reload",
      "sysdesign-kill-switch",
      "ts-adf-null-hypothesis-mcq",
      "ml-auc-vs-accuracy-when-mcq",
    ],
  },
];
